import Head from 'next/head'
import Image from 'next/image'

import useSWR from 'swr'

import styles from '../styles/Home.module.css'

const fetcher = (...args) => fetch(...args).then((res) => res.json())

export default function Home() {
  const { data: result, error } = useSWR('/api/data', fetcher)
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Quanta Code Assessment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <div>
          {JSON.stringify(result)}
        </div>

      </main>
    </div>
  )
}
